version: "3.9"

services:
  app:
    image:zinebadammiche/safedriveai-backend:latest
    build: .
    env_file: .env
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 86400; done"

volumes:
  certbot-www:
  letsencrypt:

